<?php

namespace Kodestudio\ApiResponse;

use Illuminate\Support\ServiceProvider;
use Kodestudio\ApiResponse\Helpers\ApiResponseHelper;

class ApiResponseServiceProvider extends ServiceProvider
{

    /**
     * Bootstrap any package services.
     *
     * @return void
     */
    public function boot()
    {
        $this->app->singleton(ApiResponseHelper::class, function() {
            return new ApiResponseHelper();
        });
        $this->loadRoutesFrom(__DIR__ . '/routes/web.php');
        $this->mergeConfigFrom(__DIR__ . '/config/apiresponse.php', 'apiresponse');
        $this->publishes([
            __DIR__.'/config/apiresponse.php' => config_path('apiresponse.php'),
        ]);
        /*
        $this->loadViewsFrom(__DIR__ . '/resources/views', 'contact');
        $this->loadMigrationsFrom(__DIR__ . '/database/migrations');
        */
    }

    public function register()
    {
        //parent::register(); // TODO: Change the autogenerated stub
    }
}
